# 수학과 파이썬 복습

In [2]:
import gdown
import zipfile
import os

file_id = "1dqlo0_Msev7Nh9L8GwkGCxrptmZGKseK"
gdown.download(f"https://drive.google.com/uc?id={file_id}", quiet=False)

zip_path = "/content/ai3.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("ai3")

print(f"압축 해제 완료")
os.chdir("/content/ai3/ch01")

Downloading...
From: https://drive.google.com/uc?id=1dqlo0_Msev7Nh9L8GwkGCxrptmZGKseK
To: /content/ai3.zip
100%|██████████| 8.77M/8.77M [00:00<00:00, 39.4MB/s]


압축 해제 완료


## 백터와 행렬

In [3]:
import numpy as np

x = np.array([1, 2, 3])
print(type(x))
x.__class__

<class 'numpy.ndarray'>


numpy.ndarray

In [ ]:
x.shape

(3,)

In [ ]:
len(x)

3

In [ ]:
x.shape[0]

3

In [ ]:
x.ndim

1

In [ ]:
W = np.array([[1, 2, 3], [4, 5, 6]])
W.shape

(2, 3)

In [ ]:
W.ndim

2

## 행렬의 원소별 연산

In [ ]:
W = np.array([[1, 2, 3], [4, 5, 6]])
X = np.array([[0, 1, 2], [3, 4, 5]])
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [ ]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

## 브로드 케스트

In [ ]:
A = np.array([[1, 2], [3, 4]])
A * 10

array([[10, 20],
       [30, 40]])

In [ ]:
A = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])
A * b

array([[10, 40],
       [30, 80]])

## 벡터의 내적과 행렬의 곱

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])